### ISSUE TITLE
Fatal crash when clicking the top-left "back" icon button in reader window

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1061]
I will try to reproduce this:

```
[2]   readium-desktop:sync send to 6a42f114-ccb7-4854-923b-41fc333e1cd6 +0ms
[2]   readium-desktop:sync ### action type READER_CLOSE_REQUEST +1s
[2]   readium-desktop:sync ### action type STREAMER_PUBLICATION_CLOSE_REQUEST +1ms
[2]   readium-desktop:main:redux:sagas:streamer EPUB ZIP CLEANUP: /Users/danielweck/Library/Application Support/EDRLab.ThoriumReader/publications/8f495ae4-11d0-4ecb-bde3-918cad9546da/book.epub +2m
[2] freeDestroy: Publication
[2]   r2:utils#zip/zip1 freeDestroy: Zip1 -- /Users/danielweck/Library/Application Support/EDRLab.ThoriumReader/publications/8f495ae4-11d0-4ecb-bde3-918cad9546da/book.epub +0ms
[2]   readium-desktop:main:redux:sagas:streamer STREAMER SHUTDOWN +1ms
[2]   readium-desktop:sync ### action type STREAMER_STOP_REQUEST +1ms
[2]   readium-desktop:sync ### action type STREAMER_STOP_SUCCESS +0ms
[2]   readium-desktop:sync ### action type STREAMER_PUBLICATION_CLOSE_SUCCESS +0ms
[2]   readium-desktop:main:redux:sagas:win:session:reader event close requested -> emit unregisterReader and closed +0ms
[2]   readium-desktop:main:error TypeError: Error processing argument at index 0, conversion failure from 
[2]   readium-desktop:main:error     at BrowserWindow.setBounds (electron/js2c/browser_init.js:524:21)
[2]   readium-desktop:main:error     at readerCLoseRequestFromIdentifier (/Volumes/500GB/Code/readium-desktop/dist/main.js:8230:16)
[2]   readium-desktop:main:error     at readerCLoseRequestFromIdentifier.next (<anonymous>)
[2]   readium-desktop:main:error     at next (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
[2]   readium-desktop:main:error     at currCb (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
[2]   readium-desktop:main:error     at runSelectEffect (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
[2]   readium-desktop:main:error     at runEffect (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
[2]   readium-desktop:main:error     at digestEffect (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
[2]   readium-desktop:main:error     at next (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
[2]   readium-desktop:main:error     at Object.currCb [as cont] (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
[2]   readium-desktop:main:error     at end (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1016:10)
[2]   readium-desktop:main:error     at Object.task.cont (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:840:11)
[2]   readium-desktop:main:error     at next (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1174:18)
[2]   readium-desktop:main:error     at currCb (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
[2]   readium-desktop:main:error     at takeCb (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:507:5)
[2]   readium-desktop:main:error     at put (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:343:9) +2m
[2]   readium-desktop:main:error TypeError: Error processing argument at index 0, conversion failure from 
[2]   readium-desktop:main:error     at BrowserWindow.setBounds (electron/js2c/browser_init.js:524:21)
[2]   readium-desktop:main:error     at readerCLoseRequestFromIdentifier (/Volumes/500GB/Code/readium-desktop/dist/main.js:8230:16)
[2]   readium-desktop:main:error     at readerCLoseRequestFromIdentifier.next (<anonymous>)
[2]   readium-desktop:main:error     at next (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
[2]   readium-desktop:main:error     at currCb (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
[2]   readium-desktop:main:error     at runSelectEffect (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
[2]   readium-desktop:main:error     at runEffect (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
[2]   readium-desktop:main:error     at digestEffect (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
[2]   readium-desktop:main:error     at next (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
[2]   readium-desktop:main:error     at Object.currCb [as cont] (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
[2]   readium-desktop:main:error     at end (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1016:10)
[2]   readium-desktop:main:error     at Object.task.cont (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:840:11)
[2]   readium-desktop:main:error     at next (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1174:18)
[2]   readium-desktop:main:error     at currCb (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
[2]   readium-desktop:main:error     at takeCb (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:507:5)
[2]   readium-desktop:main:error     at put (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:343:9) +2ms
[2]   readium-desktop:sync ### action type MAIN_WIN_READER_CLOSE_REQUEST +10s
[2]   readium-desktop:main:redux:sagas:win:reader reader 6a42f114-ccb7-4854-923b-41fc333e1cd6 -> winClose +2m
[2]   readium-desktop:sync ### action type WIN_SESSION_UNREGISTER_READER +1ms
[2]   readium-desktop:sync ### action type WIN_PERSIST_REQUEST +0ms
[2]   readium-desktop:sync ### action type WIN_REGISTRY_REGISTER_READER_PUBLICATION +0ms
[2]   readium-desktop:sync ### action type WIN_PERSIST_REQUEST +0ms
[2]   readium-desktop:sync ### action type STREAMER_PUBLICATION_CLOSE_REQUEST +0ms
[2]   readium-desktop:main:redux:sagas:streamer EPUB ZIP CLEANUP: /Users/danielweck/Library/Application Support/EDRLab.ThoriumReader/publications/8f495ae4-11d0-4ecb-bde3-918cad9546da/book.epub +10s
[2]   readium-desktop:main:redux:sagas:streamer STREAMER SHUTDOWN +0ms
[2]   readium-desktop:main:redux:sagas:win:reader Nb of readers: 0 +1ms
[2]   readium-desktop:main:redux:sagas:win:reader readers:  [] +0ms
[2]   readium-desktop:sync ### action type STREAMER_STOP_REQUEST +1ms
[2]   readium-desktop:sync ### action type WIN_SESSION_UNREGISTER_LIBRARY +0ms
[2]   readium-desktop:sync ### action type WIN_PERSIST_REQUEST +1ms
[2]   readium-desktop:sync ### action type STREAMER_STOP_SUCCESS +0ms
[2]   readium-desktop:sync ### action type STREAMER_PUBLICATION_CLOSE_SUCCESS +0ms
[2]   readium-desktop:sync ### action type LIBRARY_CLOSE_REQUEST +0ms
[2]   readium-desktop:main:redux:sagas:win:library library -> winClose +2m
[2]   readium-desktop:main:redux:sagas:win:library reader: [] +0ms
[2]   r2:navigator#electron/renderer/index_ [WDS] Disconnected! +12s
[2]   readium-desktop:main:saga:app ##### +2m
[2]   readium-desktop:main:saga:app ##### +1ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app window-all-closed +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:persist start of persist reduxState in disk +14s
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [default] => fulfilled +2m
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [default] => fulfilled +0ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [persist:readium2pubwebview] => fulfilled +1ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [persist:readium2pubwebview] => fulfilled +0ms
[2]   readium-desktop:main:saga:persist end of persist reduxState in disk +509ms
[2]   readium-desktop:sync ### action type STREAMER_STOP_REQUEST +589ms
[2]   readium-desktop:sync ### action type STREAMER_STOP_SUCCESS +1ms
[2]   readium-desktop:main:saga:app EXIT NOW +511ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app quit +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app ##### +0ms

```

**Comment by danielweck** [comment]
Yep, 100% reproducible. Any idea @panaC ?

**Comment by danielweck** [comment]
```
 An error has occurred in readium-desktop:main:saga:reader:readerCLoseRequestFromIdentifier
[2]   readium-desktop:main:error TypeError: Error processing argument at index 0, conversion failure from 
[2]   readium-desktop:main:error     at BrowserWindow.setBounds (electron/js2c/browser_init.js:524:21)
[2]   readium-desktop:main:error     at readerCLoseRequestFromIdentifier
```

**Comment by panaC** [comment]
I see the potential bug with setBound, but I can't reproduce it.

**Comment by danielweck** [comment]
bounds is `{ x: null, y: null, width: 1600, height: 877 }`

**Comment by panaC** [comment]
It may be possible that mac-os return null in a multi-screen configuration. I already saw it on my desk.
I surrounded setBound with a try-catch.

**Comment by danielweck** [comment]
No, I have correct `x` and `y` coordinates in my multi-display setup. I am implementing a normalization step to avoid future issues with Electron `BrowserWindow.getBounds()`.
