### ISSUE TITLE
ReadiumCSS not preserved when closing + reopening publications

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1065]
Follow-up to https://github.com/edrlab/thorium-reader/issues/1062

**Comment by danielweck** [comment]
Note that I do not use the new "sessions" feature (toggle switch in the global settings in the library window)...so every publication should have the same ReadiumCSS.

**Comment by danielweck** [comment]
When I activate the new "sessions" feature, styles are preserved correctly.

**Comment by danielweck** [comment]
When closing the library window with existing reader windows, and I accept to save the session, I see this in the console:
```
[2]   readium-desktop:main:saga:persist error persist state in user filesystem [conflict: Document update conflict] {
[2]   status: 409,
[2]   name: 'conflict',
[2]   message: 'Document update conflict',
[2]   error: true,
[2]   id: 'config_CONFIGREPOSITORY_REDUX_PERSISTENCE',
[2]   docId: 'config_CONFIGREPOSITORY_REDUX_PERSISTENCE'
[2] } +1s
[2]   readium-desktop:main:saga:persist end of persist reduxState in disk +1ms
```

**Comment by danielweck** [comment]
Also, I see the `NaN` for BrowserWindow bounds:
```
[2]   readium-desktop:main:redux:sagas:win:reader Nb of readers: 2 +2ms
[2]   readium-desktop:main:redux:sagas:win:reader readers:  [
[2]   {
[2]     windowBound: { x: NaN, y: NaN, width: 1600, height: 877 },
[2]     reduxState: { config: [Object], locator: [Object], info: [Object] },
[2]     browserWindowId: 2,
[2]     publicationIdentifier: 'aad2f9e1-68d1-419f-bc03-f0b7339edd49',
[2]     manifestUrl: 'https://127.0.0.1:8000/pub/L1VzZXJzL2RhbmllbHdlY2svTGlicmFyeS9BcHBsaWNhdGlvbiBTdXBwb3J0L0VEUkxhYi5UaG9yaXVtUmVhZGVyL3B1YmxpY2F0aW9ucy9hYWQyZjllMS02OGQxLTQxOWYtYmMwMy1mMGI3MzM5ZWRkNDkvYm9vay5lcHVi/manifest.json',
[2]     fileSystemPath: '/Users/danielweck/Library/Application Support/EDRLab.ThoriumReader/publications/aad2f9e1-68d1-419f-bc03-f0b7339edd49/book.epub',
[2]     identifier: '98335307-827f-4f86-aa9b-9fcf6411a870'
[2]   },
[2]   {
[2]     windowBound: { x: NaN, y: NaN, width: 1600, height: 877 },
[2]     reduxState: { config: [Object], locator: [Object], info: [Object] },
[2]     browserWindowId: 3,
[2]     publicationIdentifier: 'aad2f9e1-68d1-419f-bc03-f0b7339edd49',
[2]     manifestUrl: 'https://127.0.0.1:8000/pub/L1VzZXJzL2RhbmllbHdlY2svTGlicmFyeS9BcHBsaWNhdGlvbiBTdXBwb3J0L0VEUkxhYi5UaG9yaXVtUmVhZGVyL3B1YmxpY2F0aW9ucy9hYWQyZjllMS02OGQxLTQxOWYtYmMwMy1mMGI3MzM5ZWRkNDkvYm9vay5lcHVi/manifest.json',
[2]     fileSystemPath: '/Users/danielweck/Library/Application Support/EDRLab.ThoriumReader/publications/aad2f9e1-68d1-419f-bc03-f0b7339edd49/book.epub',
[2]     identifier: '9d417090-bfa1-4093-948d-42643a1999df'
[2]   }
[2] ] +0ms
```

**Comment by danielweck** [comment]
Logically, I see the consequences of `NaN`:
```
[2]   readium-desktop:main:saga:reader getWinBound(undefined) { x: NaN, y: NaN, width: 1600, height: 877 } +7s
[2]   readium-desktop:main:saga:reader error libWin.setBounds(libBound) TypeError: Error processing argument at index 0, conversion failure from 
[2]     at BrowserWindow.setBounds (electron/js2c/browser_init.js:524:21)
[2]     at readerDetachRequest (/Volumes/500GB/Code/readium-desktop/dist/main.js:8151:24)
[2]     at readerDetachRequest.next (<anonymous>)
[2]     at next (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
[2]     at Object.currCb [as cont] (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
[2]     at end (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1016:10)
[2]     at Object.task.cont (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:840:11)
[2]     at next (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1174:18)
[2]     at currCb (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
[2]     at runCallEffect (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:543:5)
[2]     at runEffect (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
[2]     at digestEffect (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
[2]     at next (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
[2]     at currCb (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
[2]     at runSelectEffect (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
[2]     at runEffect (/Volumes/500GB/Code/readium-desktop/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7) +0ms
```

**Comment by danielweck** [comment]
Another clue:
I see that the X Y coordinates are correct:

```
[2]   readium-desktop:main:redux:sagas:win:session:reader _______1 reader.getBounds() { x: 11, y: 33, width: 1600, height: 877 } +10s
```

...but moments later in the console log I see this (note the `NaN`):

```
[2]   readium-desktop:sync ### action type WIN_SESSION_SET_BOUND +2s
[2]   readium-desktop:sync ### action type WIN_PERSIST_REQUEST +0ms
[2]   readium-desktop:main:saga:persist start of persist reduxState in disk +3s
[2]   readium-desktop:main:saga:persist end of persist reduxState in disk +686ms
[2]   r2:navigator#electron/renderer/index_ Installing Devtron from /Volumes/500GB/Code/readium-desktop/node_modules/devtron +4s
[2]   r2:navigator#electron/renderer/webview/preload ANIMATION TIMEOUT REMOVE +4s
[2]   readium-desktop:main:redux:sagas:win:session:reader event close requested -> emit unregisterReader and closed +4s
[2]   readium-desktop:sync ### action type MAIN_WIN_READER_CLOSE_REQUEST +4s
[2]   readium-desktop:main:redux:sagas:win:reader reader 1f299852-38cb-47de-acd9-4c42a505489a -> winClose +7s
[2]   readium-desktop:sync ### action type WIN_SESSION_UNREGISTER_READER +0ms
[2]   readium-desktop:sync ### action type WIN_PERSIST_REQUEST +1ms
[2]   readium-desktop:sync ### action type WIN_REGISTRY_REGISTER_READER_PUBLICATION +0ms
[2]   readium-desktop:sync ### action type WIN_PERSIST_REQUEST +0ms
[2]   readium-desktop:sync ### action type STREAMER_PUBLICATION_CLOSE_REQUEST +0ms
[2]   readium-desktop:main:redux:sagas:win:reader Nb of readers: 1 +1ms
[2]   readium-desktop:main:redux:sagas:win:reader readers:  [
[2]   {
[2]     windowBound: { x: NaN, y: NaN, width: 1600, height: 877 },
[2]     reduxState: { config: [Object], locator: [Object], info: [Object] },
[2]     browserWindowId: 2,
[2]     publicationIdentifier: '8f495ae4-11d0-4ecb-bde3-918cad9546da',
[2]     manifestUrl: 'https://127.0.0.1:8000/pub/L1VzZXJzL2RhbmllbHdlY2svTGlicmFyeS9BcHBsaWNhdGlvbiBTdXBwb3J0L0VEUkxhYi5UaG9yaXVtUmVhZGVyL3B1YmxpY2F0aW9ucy84ZjQ5NWFlNC0xMWQwLTRlY2ItYmRlMy05MThjYWQ5NTQ2ZGEvYm9vay5lcHVi/manifest.json',
[2]     fileSystemPath: '/Users/danielweck/Library/Application Support/EDRLab.ThoriumReader/publications/8f495ae4-11d0-4ecb-bde3-918cad9546da/book.epub',
[2]     identifier: '5207c11c-57f2-4e81-93ac-1848d4e66712'
[2]   }
[2] ] +0ms
[2]   readium-desktop:sync ### action type STREAMER_PUBLICATION_CLOSE_SUCCESS +2ms
```

**Comment by panaC** [comment]
I can't reproduce it.

The bug is probably in this function https://github.com/edrlab/thorium-reader/blob/dfbd5ef9241774611481a1ee09239020868e7dc8/src/main/redux/sagas/reader.ts#L165

**Comment by danielweck** [comment]
Thank you for your analysis, Pierre. Let's move this x/y discussion to this issue: https://github.com/edrlab/thorium-reader/issues/1066

**Comment by danielweck** [comment]
@panaC  regarding the ReadiumCSS settings which are not saved:
1) Objectively: this is a breaking change, as the previous behaviour was that user-customized settings in the reader window were saved immediately, and restored for any subsequent publication opening (consequently, the new unexpected behaviour feels like a bug). With the new "sessions" feature (which is deactivated by default), the only difference is that opened publications have their own "context" with different settings.
2) Subjectively: the previous behaviour made a lot of sense, at least to me. The new behaviour (i.e. ReadiumCSS settings are discarded as soon as I close the reader window) is completely counter-intuitive, and frankly annoying :)

So, could we please restore the previous behaviour? If you agree, could you please implement the necessary changes? (I could probably figure out how to do it myself, but you will be able to do it much quicker)

**Comment by danielweck** [comment]
Alright, so we urgently needed a fix for this in order to restore the previous behaviour (this bug was a breaking change), and to restore MathJax functionality. As described in the commit (link below), the caveat is that the "sessions" opt-in mode is now affected in a way that is probably not desired (i.e.: all new fresh applications automatically inherits the last configuration change from other publications).

https://github.com/edrlab/thorium-reader/commit/755fdcea049b3a62f932bd19dbdb676b4fd96ba3

**Comment by danielweck** [comment]
I posted a separate issue about the "sessions" mode:
https://github.com/edrlab/thorium-reader/issues/1085
