### ISSUE TITLE
publication can be undefined in updateOpdsInfoWithEntryLink() code

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1114]
https://github.com/edrlab/thorium-reader/blob/0b7d66ef9868f6dd0993b75f448d3c262dd467f7/src/renderer/common/redux/sagas/dialog/publicationInfoOpds.ts#L47-L52

```
[2]   readium-desktop:renderer:redux:saga:publication-info-opds TypeError: Cannot read property 'authors' of undefined
[2]   readium-desktop:renderer:redux:saga:publication-info-opds     at updateOpdsInfoWithEntryLink (http://localhost:8090/index_library.js:121347:47)
[2]   readium-desktop:renderer:redux:saga:publication-info-opds     at updateOpdsInfoWithEntryLink.next (<anonymous>)
[2]   readium-desktop:renderer:redux:saga:publication-info-opds     at next (http://localhost:8090/index_library.js:2361:29)
[2]   readium-desktop:renderer:redux:saga:publication-info-opds     at currCb (http://localhost:8090/index_library.js:2455:7)
[2]   readium-desktop:renderer:redux:saga:publication-info-opds     at chCbAtKey (http://localhost:8090/index_library.js:1902:9)
[2]   readium-desktop:renderer:redux:saga:publication-info-opds     at Object.currCb [as cont] (http://localhost:8090/index_library.js:2455:7)
[2]   readium-desktop:renderer:redux:saga:publication-info-opds     at end (http://localhost:8090/index_library.js:2216:10)
[2]   readium-desktop:renderer:redux:saga:publication-info-opds     at Object.task.cont (http://localhost:8090/index_library.js:2040:11)
[2]   readium-desktop:renderer:redux:saga:publication-info-opds     at next (http://localhost:8090/index_library.js:2374:18)
[2]   readium-desktop:renderer:redux:saga:publication-info-opds     at currCb (http://localhost:8090/index_library.js:2455:7) +2ms
```

Reproducible with OPDS feed: https://textos.info/opds
("about book", then check the console)

**Comment by danielweck** [comment]
To quickly visualize the feed: https://readium2.herokuapp.com/opds-v1-v2-convert/https%3A%2F%2Ftextos.info%2Fopds

**Comment by panaC** [comment]
fixed
