### ISSUE TITLE
bug: crash while importing a JSON doc which is not an LCP license 

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1254]
Requested a license from the License Server via the API with a wrong content id.
Didn't check the response, saved it in a .lcpl file.
Dropped the file in Thorium.

Content of the file is 
```{"title":"Internal Server Error","status":500,"detail":"Content not found"}```

**Comment by panaC** [comment]
```
[2]   readium-desktop:main:saga:api publication importFromFs [ [ '/Users/Pierre/Desktop/test-fake.lcpl' ] ] +1m
[2]   readium-desktop:main#saga/api/publication/importFromFSService importFromFsService /Users/Pierre/Desktop/test-fake.lcpl +1m
[2]   readium-desktop:main#saga/api/publication/importFromFSService extension .lcpl +0ms
[2]   readium-desktop:main#saga/api/publication/importFromFSService lcp/lpf/pdf true false false +0ms
[2]   readium-desktop:main#saga/api/publication/importFromFSService is a LCP licence need a converter +0ms
[2]   r2:lcp#parser/epub/lcp LCP _usesNativeNodePlugin +6m
[2]   r2:lcp#parser/epub/lcp /Users/Pierre/Documents/thorium/dist/external-assets +0ms
[2]   r2:lcp#parser/epub/lcp lcp.node +0ms
[2]   r2:lcp#parser/epub/lcp server => Apache +138ms
[2]   r2:lcp#parser/epub/lcp last-modified => Tue, 10 Nov 2020 11:55:02 GMT +0ms
[2]   r2:lcp#parser/epub/lcp etag => "1c1-5b3bf594eb7a8" +0ms
[2]   r2:lcp#parser/epub/lcp accept-ranges => bytes +0ms
[2]   r2:lcp#parser/epub/lcp content-length => 449 +0ms
[2]   r2:lcp#parser/epub/lcp content-type => application/pkix-crl +0ms
[2]   r2:lcp#parser/epub/lcp cache-control => max-age=7440 +0ms
[2]   r2:lcp#parser/epub/lcp date => Tue, 10 Nov 2020 18:11:39 GMT +0ms
[2]   r2:lcp#parser/epub/lcp connection => close +0ms
[2]   r2:lcp#parser/epub/lcp -----BEGIN X509 CRL-----
[2]   r2:lcp#parser/epub/lcp MIIBvTCBpgIBATANBgkqhkiG9w0BAQsFADBCMRMwEQYDVQQKEwplZHJsYWIub3JnMRcwFQYDVQQLEw5lZHJsYWIub3JnIExDUDESMBAGA1UEAxMJRURSTGFiIENBFw0yMDExMTAxMTUwMDVaFw0yMDExMTUxMTUwMDVaoDAwLjAfBgNVHSMEGDAWgBTcXPyT5B+f7rC66lILK8pSXODJhzALBgNVHRQEBAICBaUwDQYJKoZIhvcNAQELBQADggEBAEk6IAidDxlpEzTDdu2VXfo3Suvx/AKcK8JIOUpQe0npSf7txmkU6p6NJ6hOy/ncAlgKEmgAkBFwFQv+w28in5+z8DhFabocCP526HA0luTlPjTqVRfXUEjrO68dMD8MRx6z6cIttchbChGF15HaMqLxj4w1iWLXXfs541PCe3qqpb5ybXchJETL5EA3awnCLdYrGka9L+hAtSQ48PaYCGWO792CTgh2/lPVAv52aRRTxfWcZ4UaCWzQWze2eBGuAeZFS8pY9ZbQZYlSomboswOPFSCKLCA7DF6utKil0oHlt9eDn5x7Yb5DzFquK0kuvoyxvAgBf0RlIBqwS7REKEk=
[2]   r2:lcp#parser/epub/lcp -----END X509 CRL----- +2ms
[2] libc++abi.dylib: terminating with uncaught exception of type std::logic_error: id value cannot not be null
[3] 1605031899879 - Origin: Worker (PID 11188)
[3]    [Warning] SocketProtocolError: Socket hung up
[3]     at SCServerSocket._onSCClose (/Users/Pierre/Documents/thorium/node_modules/socketcluster-server/scserversocket.js:267:17)
[3]     at WebSocket.<anonymous> (/Users/Pierre/Documents/thorium/node_modules/socketcluster-server/scserversocket.js:80:10)
[3]     at WebSocket.emit (events.js:315:20)
[3]     at WebSocket.emitClose (/Users/Pierre/Documents/thorium/node_modules/socketcluster-server/node_modules/ws/lib/websocket.js:193:10)
[3]     at Socket.socketOnClose (/Users/Pierre/Documents/thorium/node_modules/socketcluster-server/node_modules/ws/lib/websocket.js:861:15)
[3]     at Socket.emit (events.js:315:20)
[3]     at TCP.<anonymous> (net.js:674:12)
[2] npm run start:dev:main exited with code 0
--> Sending SIGTERM to other processes..
[3] npm run redux-devtools exited with code 0
--> Sending SIGTERM to other processes..
[1] npm run start:dev:renderer:reader exited with code 0
--> Sending SIGTERM to other processes..
[0] npm run start:dev:renderer:library exited with code SIGTERM
```

Thorium crash instantly
