### ISSUE TITLE
npm install fails on Linux

### ISSUE THREAD

**Issue by VK2BEA** [edrlab/thorium-reader#1260]
```
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Linux 5.8.18-300.fc33.x86_64
gyp ERR! command "/usr/bin/node" "/home/michael/Downloads/thorium-reader/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/michael/Downloads/thorium-reader/node_modules/leveldown
gyp ERR! node -v v14.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@5.6.0 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@5.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/michael/.npm/_logs/2020-11-18T15_20_26_060Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EDRLab.ThoriumReader@1.6.0-alpha.1 postinstall: `npm run rmLevelDownDeep && npm run rmLevelDownPrebuilds && npm rebuild --runtime=electron --target=9.3.4 --disturl=https://atom.io/download/atom-shell --build-from-source`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the EDRLab.ThoriumReader@1.6.0-alpha.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/michael/.npm/_logs/2020-11-18T15_20_26_388Z-debug.log

```

**Comment by danielweck** [comment]
Hello, please make sure to have Python 2.x as the default on your Linux computer (this is usually the case, as Python 3.x introduces breaking changes / incompatibilities).
