### ISSUE TITLE
HTTPS to HTTP redirect fails (affects OPDS, and other transactions based on Thorium's network request stack)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1323]
`TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:`
`API-ERROR TypeError: Cannot read property 'headers' of undefined`

https://textos.info/opds

(see https://readium2.herokuapp.com/opds-v1-v2-convert/https%3A%2F%2Ftextos.info%2Fopds )

```
[2]   readium-desktop:renderer:redux:saga:opds opds browse url= https://textos.info/opds +2ms
[2]   readium-desktop:renderer:redux:saga:opds-browse opds-browse https://textos.info/opds +1ms
[2]   readium-desktop:sync ### action type API_REQUEST +708ms
[2]   readium-desktop:main:saga:api opds browse [ 'https://textos.info/opds' ] +709ms
[2]   readium-desktop:main/http fetch URL: https://textos.info/opds +0ms
[2]   readium-desktop:main/http Method get +0ms
[2]   readium-desktop:main/http Request headers : +0ms
[2]   readium-desktop:main/http Headers {
[2]   readium-desktop:main/http   [Symbol(map)]: [Object: null prototype] {
[2]   readium-desktop:main/http     'user-agent': [ 'readium-desktop' ],
[2]   readium-desktop:main/http     'accept-language': [ 'en,en-US;q=0.7,en;q=0.5' ],
[2]   readium-desktop:main/http     cookie: [ '' ]
[2]   readium-desktop:main/http   }
[2]   readium-desktop:main/http } +0ms
[2]   readium-desktop:main/http ### +1ms
[2]   readium-desktop:main/http OK:  false +0ms
[2]   readium-desktop:main/http status code : 301 +0ms
[2]   readium-desktop:main/http status text : Moved Permanently +0ms
[2]   readium-desktop:main/http Redirect 301 to:  http://www.textos.info/opds +0ms
[2]   readium-desktop:main/http TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:" +7ms
[2]   readium-desktop:main:saga:api API-ERROR TypeError: Cannot read property 'headers' of undefined
[2]     at OpdsService.<anonymous> (thorium/dist/main.js:13029:67)
[2]     at Generator.next (<anonymous>)
[2]     at thorium/node_modules/tslib/tslib.js:117:75
[2]     at new Promise (<anonymous>)
[2]     at Object.__awaiter (thorium/node_modules/tslib/tslib.js:113:16)
[2]     at thorium/dist/main.js:13010:85
[2]     at thorium/dist/main.js:5904:37
[2]     at Generator.next (<anonymous>)
[2]     at thorium/node_modules/tslib/tslib.js:117:75
[2]     at new Promise (<anonymous>)
[2]     at Object.__awaiter (thorium/node_modules/tslib/tslib.js:113:16)
[2]     at handleCallback (thorium/dist/main.js:5902:51)
[2]     at thorium/dist/main.js:6001:26
[2]     at Generator.next (<anonymous>)
[2]     at fulfilled (thorium/node_modules/tslib/tslib.js:114:62)
[2]     at processTicksAndRejections (internal/process/task_queues.js:94:5) requestAction:  {
[2]   type: 'API_REQUEST',
[2]   payload: [ 'https://textos.info/opds' ],
[2]   meta: {
[2]     api: {
[2]       requestId: 'browseOpdsApiResult',
[2]       moduleId: 'opds',
[2]       methodId: 'browse'
[2]     }
[2]   },
[2]   sender: { type: 1, identifier: 'aa2fe7f3-3924-40ee-9941-14ed2f17fd83' }
[2] } +379ms
[2]   readium-desktop:sync ### action type API_RESULT +380ms
[2]   readium-desktop:sync send to aa2fe7f3-3924-40ee-9941-14ed2f17fd83 +0ms
[2]   readium-desktop:renderer:redux:saga:opds-browse opds-browse action-received {
[2]   type: 'API_RESULT',
[2]   payload: CodeError: Cannot read property 'headers' of undefined
[2]       at Function.fromJson (http://localhost:8090/index_library.js:114946:16)
[2]       at Function.deserialize (http://localhost:8090/index_library.js:117031:54)
[2]       at EventEmitter.<anonymous> (http://localhost:8090/index_library.js:124682:76)
[2]       at EventEmitter.emit (events.js:223:5)
[2]       at Object.onMessage (electron/js2c/renderer_init.js:115:818) {
[2]     code: 'API-ERROR'
[2]   },
[2]   meta: {
[2]     api: {
[2]       requestId: 'browseOpdsApiResult',
[2]       moduleId: 'opds',
[2]       methodId: 'browse'
[2]     }
[2]   },
[2]   error: true,
[2]   sender: { type: 0 }
[2] } +388ms
[2]   readium-desktop:renderer:redux:saga:opds opds browse data received +2ms
[2]   readium-desktop:sync ### action type API_REQUEST +4m
[2]   readium-desktop:main:saga:api opds findAllFeeds [] +4m
[2]   readium-desktop:sync ### action type API_RESULT +1ms
[2]   readium-desktop:sync send to aa2fe7f3-3924-40ee-9941-14ed2f17fd83 +0ms
```

**Comment by danielweck** [comment]
Works fine with the non-redirect (HTTP 301) URL: https://www.textos.info/opds

**Comment by danielweck** [comment]
Also works fine with http://www.textos.info/opds (HTTP 301 redirect to the canonical secure HTTP https://www.textos.info/catalogo.atom )

**Comment by danielweck** [comment]
According to the NodeFetch documentation, a custom Agent can be used to ensure the correct HTTP(S) protocol during a redirection chain:
https://github.com/node-fetch/node-fetch#custom-agent
```
const http = require('http');
const https = require('https');

const httpAgent = new http.Agent({
	keepAlive: true
});
const httpsAgent = new https.Agent({
	keepAlive: true
});

const options = {
	agent: function(_parsedURL) {
		if (_parsedURL.protocol == 'http:') {
			return httpAgent;
		} else {
			return httpsAgent;
		}
	}
};
```

Thorium code:
https://github.com/edrlab/thorium-reader/blob/603c65cef4ebfec9fb3492e99cf923feeb2b0c51/src/main/network/http.ts#L126-L132

**Comment by danielweck** [comment]
I have added this to 1.6 TODO, on the basis that HTTPS-HTTP downgraded redirection could occur in any / many situations (in the case of Textos OPDS, the redirection chain terminates at HTTPS, but with HTTP intermediary).

**Comment by danielweck** [comment]
For illustration purposes, here is the Textos.info specific HTTP redirect chain:

`curl --verbose -L https://textos.info/opds`

=>

* HTTP/1.1 301 Moved Permanently Location: http://www.textos.info/opds
* HTTP/1.1 301 Moved Permanently Location: https://www.textos.info/opds
* HTTP/1.1 301 Moved Permanently Location: https://www.textos.info/catalogo.atom
* HTTP/1.1 200 OK

**Comment by danielweck** [comment]
Related issue: https://github.com/edrlab/thorium-reader/issues/1314

**Comment by panaC** [comment]
https to http redirect shouldn't allowed. Is it really usefull to invest our time on it ?

**Comment by danielweck** [comment]
> Is it really usefull to invest our time on it ?

I agree that our development priorities should be reviewed carefully, and this edge-case is not blocking the 1.6 release.

Let's keep the issue open to address the issue of HTTP(S) Agent in general, which will in turn fix the HTTP redirection bug:

https://github.com/edrlab/thorium-reader/blob/1a01c03e74d1504b0a521898f1ca76b5f6484cfc/src/main/network/http.ts#L110-L132

**Comment by danielweck** [comment]
With Thorium from the current `develop` branch, OPDS `https://textos.info/opds`:

<img width="1350" alt="Screenshot 2021-09-02 at 15 52 12" src="https://user-images.githubusercontent.com/625201/131866234-f7486331-ce5d-4e5c-aaf0-5fde2a482c9e.png">

**Comment by danielweck** [comment]
Code reference: https://github.com/edrlab/thorium-reader/blob/d6991b095d37fbfe7121ad43f45aa0daa583ff3e/src/main/network/http.ts#L228-L250
