### ISSUE TITLE
dev: JEST tests are broken?

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1697]
```
> cross-env JEST_TESTS=1 jest --config=jest.config.js --verbose --runInBand --bail=1 --no-cache "test"

PREPROCESSOR nodeEnv: test
FAIL test/lpfConverter.test.ts
  ● Test suite failed to run

    TypeError: src.indexOf is not a function

      23 |         let needsPatching = false;
      24 |         for (const key of preProcessorKeys) {
    > 25 |             needsPatching = src.indexOf(key) >= 0;
         |                                 ^
      26 |             if (needsPatching) {
      27 |                 // console.log(`================ JEST TRANSFORM PROCESS: ${filename}`);
      28 |                 break;

      at Object.process (scripts/jest_preprocessor.js:25:33)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:822:19)

FAIL test/utils/iso8601.test.ts
  ● Test suite failed to run

    TypeError: src.indexOf is not a function

      23 |         let needsPatching = false;
      24 |         for (const key of preProcessorKeys) {
    > 25 |             needsPatching = src.indexOf(key) >= 0;
         |                                 ^
      26 |             if (needsPatching) {
      27 |                 // console.log(`================ JEST TRANSFORM PROCESS: ${filename}`);
      28 |                 break;

      at Object.process (scripts/jest_preprocessor.js:25:33)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:822:19)

FAIL test/utils/mimeTypes.test.ts
  ● Test suite failed to run

    TypeError: src.indexOf is not a function

      23 |         let needsPatching = false;
      24 |         for (const key of preProcessorKeys) {
    > 25 |             needsPatching = src.indexOf(key) >= 0;
         |                                 ^
      26 |             if (needsPatching) {
      27 |                 // console.log(`================ JEST TRANSFORM PROCESS: ${filename}`);
      28 |                 break;

      at Object.process (scripts/jest_preprocessor.js:25:33)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:822:19)

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        7.588 s
Ran all test suites matching /test/i.
Error: Process completed with exit code 1.
```

**Comment by danielweck** [comment]
bug triage: thorium's unit / integration tests are frankly quite useless at the moment, a complete overhaul would be needed to achieve useful coverage. Closing.
