### ISSUE TITLE
regression in OpdsControl component

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#1800]
```
OpdsControls.tsx:27 Uncaught TypeError: Cannot read properties of undefined (reading 'indirectAcquisitionType')
    at OpdsControls.tsx:27:1
    at Array.sort (<anonymous>)
    at orderLinks (OpdsControls.tsx:26:1)
    at openAccessLinksButton (OpdsControls.tsx:43:1)
    at OpdsControls.render (OpdsControls.tsx:96:1)
    at finishClassComponent (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:17485:31)
    at updateClassComponent (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:17435:24)
    at beginWork (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:19073:16)
    at HTMLUnknownElement.callCallback (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
(anonymous) @ OpdsControls.tsx:27
orderLinks @ OpdsControls.tsx:26
openAccessLinksButton @ OpdsControls.tsx:43
render @ OpdsControls.tsx:96
finishClassComponent @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:17485
updateClassComponent @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:17435
beginWork @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:19073
callCallback @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:4056
beginWork$1 @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:23964
performUnitOfWork @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22779
workLoopSync @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22707
renderRootSync @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22670
performSyncWorkOnRoot @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22293
(anonymous) @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11327
unstable_runWithPriority @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11276
flushSyncCallbackQueueImpl @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11322
flushSyncCallbackQueue @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11309
discreteUpdates$1 @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22420
discreteUpdates @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3756
dispatchDiscreteEvent @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:5889
/home/pierre/Documents/edrlab/thorium-reader/node_modules/r2-navigator-js/dist/es8-es2017/src/electron/renderer/common/console-redirect.js:74 The above error occurred in the <OpdsControls> component:

    at OpdsControls (http://localhost:8090/index_library.js:15760:9)
    at WrapperComponent (http://localhost:8090/index_library.js:12769:30)
    at ConnectFunction (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-redux/lib/components/connectAdvanced.js:235:41)
    at div
    at div
    at PublicationInfoContent (http://localhost:8090/index_library.js:12491:13)
    at div
    at div
    at div
    at div
    at FocusLockUI (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-focus-lock/dist/cjs/Lock.js:40:31)
    at FocusLockUICombination
    at Dialog (http://localhost:8090/index_library.js:11825:9)
    at WrapperComponent (http://localhost:8090/index_library.js:12769:30)
    at PublicationInfoManager (http://localhost:8090/index_library.js:12576:13)
    at WrapperComponent (http://localhost:8090/index_library.js:12769:30)
    at PublicationInfo (http://localhost:8090/index_library.js:15350:9)
    at WrapperComponent (http://localhost:8090/index_library.js:12769:30)
    at ConnectFunction (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-redux/lib/components/connectAdvanced.js:235:41)
    at DialogManager (http://localhost:8090/index_library.js:14801:9)
    at ConnectFunction (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-redux/lib/components/connectAdvanced.js:235:41)
    at div
    at /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dropzone/dist/index.js:1:13327
    at Router (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-router/umd/react-router.development.js:821:17)
    at HistoryRouter (/home/pierre/Documents/edrlab/thorium-reader/node_modules/redux-first-history/rr6/index.js:11:22)
    at Provider (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-redux/lib/components/Provider.js:21:20)
    at App (http://localhost:8090/index_library.js:13386:9)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
newConsoleFunction @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/r2-navigator-js/dist/es8-es2017/src/electron/renderer/common/console-redirect.js:74
logCapturedError @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:20085
update.callback @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:20118
callCallback @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:12318
commitUpdateQueue @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:12339
commitLifeCycles @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:20736
commitLayoutEffects @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:23426
callCallback @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:4056
commitRootImpl @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:23151
unstable_runWithPriority @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11276
commitRoot @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22990
performSyncWorkOnRoot @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22329
(anonymous) @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11327
unstable_runWithPriority @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11276
flushSyncCallbackQueueImpl @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11322
flushSyncCallbackQueue @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11309
discreteUpdates$1 @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22420
discreteUpdates @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3756
dispatchDiscreteEvent @ /home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:5889
/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11340 Uncaught TypeError: Cannot read properties of undefined (reading 'indirectAcquisitionType')
    at OpdsControls.tsx:27:1
    at Array.sort (<anonymous>)
    at orderLinks (OpdsControls.tsx:26:1)
    at openAccessLinksButton (OpdsControls.tsx:43:1)
    at OpdsControls.render (OpdsControls.tsx:96:1)
    at finishClassComponent (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:17485:31)
    at updateClassComponent (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:17435:24)
    at beginWork (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:19073:16)
    at HTMLUnknownElement.callCallback (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (/home/pierre/Documents/edrlab/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
```
https://opds-auth-test-server-aplqpqv3wa-ey.a.run.app/ 

public -> accessible epub 3 publication

**Comment by panaC** [comment]
I think the regression come from this commit : https://github.com/edrlab/thorium-reader/commit/09ae89c0585b91556cc8ca77fbbcb3f288c6cfd5
