### ISSUE TITLE
Corrupted persistent state messages in console

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2211]
First launch from scratch (deleted `EDRLab.ThoriumReader`):

```
[2]   readium-desktop:main:di initStore +0ms
[2]   readium-desktop:main:store:memory  +0ms
[2]   readium-desktop:main:store:memory MEMORY INIT STORE +0ms
[2]   readium-desktop:main:store:memory N-1 STATE + PATCH != STATE +162ms
[2]   readium-desktop:main:store:memory Your state is probably corrupted +39ms
[2]   readium-desktop:main:store:memory If it is a fresh thorium installation do not worry +20ms
[2]   readium-desktop:main:store:memory If it is a migration from Thorium 1.6 to Thorium 1.7 do not worry too, migrtion process will start +36ms
[2]   readium-desktop:main:store:memory AssertionError [ERR_ASSERTION]: ?!
[2]   readium-desktop:main:store:memory     at new AssertionError (node:internal/assert/assertion_error:451:5)
[2]   readium-desktop:main:store:memory     at ok (/Users/danielweck/Code/readium-desktop/dist/main.js:3616:11)
[2]   readium-desktop:main:store:memory     at runtimeState (/Users/danielweck/Code/readium-desktop/dist/main.js:14529:74)
[2]   readium-desktop:main:store:memory     at async initStore (/Users/danielweck/Code/readium-desktop/dist/main.js:14572:44)
[2]   readium-desktop:main:store:memory     at async createStoreFromDi (/Users/danielweck/Code/readium-desktop/dist/main.js:5330:35)
[2]   readium-desktop:main:store:memory     at async start (/Users/danielweck/Code/readium-desktop/dist/main.js:16119:11)
[2]   readium-desktop:main:store:memory     at async Promise.all (index 0)
[2]   readium-desktop:main:store:memory     at async mainCommand (/Users/danielweck/Code/readium-desktop/dist/main.js:3892:5)
[2]   readium-desktop:main:store:memory     at async Object.handler (/Users/danielweck/Code/readium-desktop/dist/main.js:3979:5) +20ms
[2]   readium-desktop:main:store:memory REDUX STATE IS CORRUPTED THE TEST FAILED +59ms
[2]   readium-desktop:main:store:memory For security purpose the state is not erase +0ms
[2]   readium-desktop:main:store:memory Be carefull, an unexpected behaviour may occur +1ms
[2]   readium-desktop:main:store:memory RECOVERY FAILED none of the 4 recoveries mode worked +0ms
[2]   readium-desktop:main:store:memory RECOVERY : a state backup file is copied in /Users/danielweck/Library/Application Support/EDRLab.ThoriumReader/config-data-json-dev/state.1715876184534.json +2ms
[2]   readium-desktop:main:store:memory keep it safe, you may restore a corrupted state with it +0ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [persist:readium2pubwebview] => fulfilled +0ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [persist:readium2pubwebview] => fulfilled +0ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [default] => fulfilled +0ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [default] => fulfilled +0ms
[2]   readium-desktop:main:store:memory ####### WARNING ###### +4ms
[2]   readium-desktop:main:store:memory Thorium starts with a fresh new session +1ms
[2]   readium-desktop:main:store:memory There are no DATABASE on the filesystem +0ms
[2]   readium-desktop:main:store:memory ####### WARNING ###### +0ms
[2]   readium-desktop:main:store:memory REDUX STATE VALUE ::  undefined nil +0ms
[2]   readium-desktop:main:di store loaded +581ms
[2]   readium-desktop:main:di container store and saga binded +0ms
[2]   readium-desktop:main/start store loaded +0ms
[2]   readium-desktop:sync ### action type APP_INIT_REQUEST +0ms
[2]   readium-desktop:main/start STORE MOUNTED -> MOUNTING THE APP NOW +4ms
[2]   readium-desktop:main:saga:app Main app ready +0ms
```

**Comment by danielweck** [comment]
Second launch:

```
[2]   readium-desktop:main:di initStore +0ms
[2]   readium-desktop:main:store:memory  +0ms
[2]   readium-desktop:main:store:memory MEMORY INIT STORE +0ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [persist:readium2pubwebview] => fulfilled +0ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [persist:readium2pubwebview] => fulfilled +0ms
[2]   readium-desktop:main:store:memory STATE LOADED FROM FS +187ms
[2]   readium-desktop:main:store:memory 😍😍😍😍😍😍😍😍 +1ms
[2]   readium-desktop:main:store:memory N-1 STATE + PATCH != STATE +4ms
[2]   readium-desktop:main:store:memory Your state is probably corrupted +20ms
[2]   readium-desktop:main:store:memory If it is a fresh thorium installation do not worry +0ms
[2]   readium-desktop:main:store:memory If it is a migration from Thorium 1.6 to Thorium 1.7 do not worry too, migrtion process will start +19ms
[2]   readium-desktop:main:store:memory AssertionError [ERR_ASSERTION]: ?!
[2]   readium-desktop:main:store:memory     at new AssertionError (node:internal/assert/assertion_error:451:5)
[2]   readium-desktop:main:store:memory     at ok (/Users/danielweck/Code/readium-desktop/dist/main.js:3616:11)
[2]   readium-desktop:main:store:memory     at runtimeState (/Users/danielweck/Code/readium-desktop/dist/main.js:14529:74)
[2]   readium-desktop:main:store:memory     at async initStore (/Users/danielweck/Code/readium-desktop/dist/main.js:14572:44)
[2]   readium-desktop:main:store:memory     at async createStoreFromDi (/Users/danielweck/Code/readium-desktop/dist/main.js:5330:35)
[2]   readium-desktop:main:store:memory     at async start (/Users/danielweck/Code/readium-desktop/dist/main.js:16119:11)
[2]   readium-desktop:main:store:memory     at async Promise.all (index 0)
[2]   readium-desktop:main:store:memory     at async mainCommand (/Users/danielweck/Code/readium-desktop/dist/main.js:3892:5)
[2]   readium-desktop:main:store:memory     at async Object.handler (/Users/danielweck/Code/readium-desktop/dist/main.js:3979:5) +1ms
[2]   readium-desktop:main:store:memory RECOVERY : the state is provided from potentially corrupted state.json file +1ms
[2]   readium-desktop:main:store:memory the last state.json seems good after a quick test on it ! +20ms
[2]   readium-desktop:main:store:memory state - 1 + patch is not used +3ms
[2]   readium-desktop:main:store:memory recovery state come from state.json +0ms
[2]   readium-desktop:main:store:memory REVOVERY WORKS lvl 2/4 +0ms
[2]   readium-desktop:main:store:memory RECOVERY : a state backup file is copied in /Users/danielweck/Library/Application Support/EDRLab.ThoriumReader/config-data-json-dev/state.1715876414352.json +4ms
[2]   readium-desktop:main:store:memory keep it safe, you may restore a corrupted state with it +1ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [default] => fulfilled +75ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [default] => fulfilled +0ms
[2]   readium-desktop:main:store:memory REDUX STATE VALUE ::  object [
[2]   'theme',       'win',
[2]   'publication', 'reader',
[2]   'session',     'i18n',
[2]   'opds',        'version',
[2]   'wizard'
[2] ] +2ms
[2]   readium-desktop:main:di store loaded +392ms
[2]   readium-desktop:main:di container store and saga binded +0ms
[2]   readium-desktop:main/start store loaded +0ms
[2]   readium-desktop:sync ### action type APP_INIT_REQUEST +0ms
[2]   readium-desktop:keyboard Keyboard shortcuts from user (true): +0ms
[2]   readium-desktop:main/start STORE MOUNTED -> MOUNTING THE APP NOW +7ms
[2]   readium-desktop:main:saga:app Main app ready +0ms

```

**Comment by panaC** [comment]
Third : 

```
[2]   readium-desktop:main:di initStore +0ms
[2]   readium-desktop:main:store:memory  +0ms
[2]   readium-desktop:main:store:memory MEMORY INIT STORE +1ms
[2]   readium-desktop:main:store:memory STATE LOADED FROM FS +111ms
[2]   readium-desktop:main:store:memory 😍😍😍😍😍😍😍😍 +0ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [persist:readium2pubwebview] => fulfilled +0ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [persist:readium2pubwebview] => fulfilled +0ms
[2]   readium-desktop:main:store:memory hydration state is certified compliant +2ms
[2]   readium-desktop:main:store:memory RECOVERY WORKS lvl 1/4 +0ms
[2]   readium-desktop:main:store:memory REDUX STATE VALUE ::  object [
[2]   'theme',       'win',
[2]   'publication', 'reader',
[2]   'session',     'i18n',
[2]   'opds',        'version',
[2]   'wizard'
[2] ] +6ms
```

**Comment by panaC** [comment]
runtimeStateFilePath is not writed on the second launch but on the third, I don't remember why for the moment.
https://github.com/edrlab/thorium-reader/blob/aec97c6e012d5b0c49dd95fb692ed568e4a4b4ee/src/main/redux/store/memory.ts#L185-L191

**Comment by danielweck** [comment]
try catch finally cascades ... maybe time to refactor Thorium to EffectTS :D
