### ISSUE TITLE
Error opening epub ebook file

### ISSUE THREAD

**Issue by planetkalpesh** [edrlab/thorium-reader#2474]
This is the error I get opening epub file:

Importing [D:\Tuts\Reading\Books\SRL\Mortimer J Adler - How_to_Read_a_Book.epub] failed: [Error: Invalid comment length. Expected: 1. Found: 0. Are there extra bytes at the end of the file? Or is the end of central dir signature `PK☺☻` in the comment?]

I have attached epub file renamed as zip extension. Rename it as epub extension to view the file.
[Mortimer J Adler - How_to_Read_a_Book.zip](https://github.com/user-attachments/files/16022644/Mortimer.J.Adler.-.How_to_Read_a_Book.zip)

**Comment by panaC** [comment]
There are an issue with the zip archive : 

![image](https://github.com/edrlab/thorium-reader/assets/3198865/10ad4479-9d47-46a0-aaa2-7421161cd482)

note in thorium : 

```
[2]   readium-desktop:main#saga/api/publication/import importFromFs (hash + import) fail with :/Users/edrlab/Downloads/Mortimer.J.Adler.-.How_to_Read_a_Book.zip Error: Invalid comment length. Expected: 1. Found: 0. Are there extra bytes at the end of the file? Or is the end of central dir signature `PK☺☻` in the comment?
[2]     at /Users/edrlab/Documents/edrlab/projects/thorium-project/thorium-reader/node_modules/yauzl/index.js:134:25
[2]     at /Users/edrlab/Documents/edrlab/projects/thorium-project/thorium-reader/node_modules/yauzl/index.js:705:5
[2]     at /Users/edrlab/Documents/edrlab/projects/thorium-project/thorium-reader/node_modules/yauzl/fd-slicer.js:33:7
```

**Comment by planetkalpesh** [comment]
> If i open the publication in calibre after rename it to the .epub extension, Calibre fix the zip issue and it can be imported/opened in thorium now

I have directly opened the epub file in Thorium Reader and it gave me that error

**Comment by planetkalpesh** [comment]
The solution was to convert epub to epub in calibre ebook manager and the converted epub is working fine.
