### ISSUE TITLE
OPDS : epub download error on manybook.net

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#828]
![image](https://user-images.githubusercontent.com/3198865/67639278-3c5acf80-f8ee-11e9-8a56-6650918ded0a.png)

```
readium-desktop:main#services/catalog [START] Download publication http://srv.manybooks.net/send/1:epub:.epub:epub/ruskinjo2589725897-8/ruskinjo2589725897-8.epub +0ms
[2]   readium-desktop:main#services/catalog importOpdsPublication - FAIL {
[2]   Metadata: {
[2]     Title: 'Aratra Pentelici, Seven Lectures on the Elements of Sculpture',
[2]     Identifier: 'urn:manybooks:b45f4d82-e188-cda4-0e00-72d055562088',
[2]     Modified: '2019-10-27T18:11:05.000Z',
[2]     Author: [ [Object] ],
[2]     Description: '\n' +
[2]       '\t\t  <div xmlns="http://www.w3.org/1999/xhtml"><strong>Subtitle: </strong>Given before the University of Oxford in Michaelmas Term, 1870<br/><br/><strong>Published:</strong> 1870<br/><strong>Language</strong>: en</div>\n' +
[2]       '\t\t'
[2]   },
[2]   Links: [
[2]     {
[2]       Href: 'http://srv.manybooks.net/covers/ruskinjo2589725897-8.jpg',
[2]       TypeLink: 'image/jpeg',
[2]       Rel: [Array]
[2]     },
[2]     {
[2]       Href: 'http://srv.manybooks.net/thumbnails/ruskinjo2589725897-8.jpg',
[2]       TypeLink: 'image/jpeg',
[2]       Rel: [Array]
[2]     },
[2]     {
[2]       Href: 'http://srv.manybooks.net/send/1:epub:.epub:epub/ruskinjo2589725897-8/ruskinjo2589725897-8.epub',
[2]       TypeLink: 'application/epub+zip',
[2]       Rel: [Array]
[2]     }
[2]   ]
[2] } Error: ESOCKETTIMEDOUT
[2]     at ClientRequest.<anonymous> (/home/pierre/Documents/edrlab/thorium/node_modules/request/request.js:816:19)
[2]     at Object.onceWrapper (events.js:291:20)
[2]     at ClientRequest.emit (events.js:203:13)
[2]     at Socket.emitRequestTimeout (_http_client.js:680:40)
[2]     at Object.onceWrapper (events.js:291:20)
[2]     at Socket.emit (events.js:203:13)
[2]     at Socket._onTimeout (net.js:434:8)
[2]     at listOnTimeout (internal/timers.js:531:17)
[2]     at processTimers (internal/timers.js:475:7) {
[2]   code: 'ESOCKETTIMEDOUT',
[2]   connect: false
[2] } +0ms
[2]   readium-desktop:sync ### action type TOAST_OPEN_REQUEST +5s
[2]   readium-desktop:main#redux/sagas/api Error: importOpdsPublication Error: ESOCKETTIMEDOUT
[2]   readium-desktop:main#redux/sagas/api     at PublicationApi.<anonymous> (/home/pierre/Documents/edrlab/thorium/dist/main.js:2032:27)
[2]   readium-desktop:main#redux/sagas/api     at Generator.throw (<anonymous>)
[2]   readium-desktop:main#redux/sagas/api     at rejected (/home/pierre/Documents/edrlab/thorium/node_modules/tslib/tslib.js:108:69)
[2]   readium-desktop:main#redux/sagas/api     at processTicksAndRejections (internal/process/task_queues.js:85:5) +5s
[2]   readium-desktop:sync ### action type API_ERROR +3ms
[2]   readium-desktop:renderer:bookshelf_ Error to fetch api publication/importOpdsEntry API Timeout +9s
```

epub link : http://srv.manybooks.net/send/1:epub:.epub:epub/ruskinjo2589725897-8/ruskinjo2589725897-8.epub

http://readium2.herokuapp.com/opds-v1-v2-convert/http%3A%2F%2Fmanybooks.net%2Fopds%2Ftitle_detail.php%3Ftid%3Druskinjo2589725897-8

**Comment by panaC** [comment]
It works now
