### ISSUE TITLE
Allow self-signed certificates in dev mode

### ISSUE THREAD

**Issue by iisisrael** [edrlab/thorium-reader#860]
When running in dev mode (`npm run start:dev`), self-signed certificates should be allowed so requests can be made to a dev / test catalog provider.  Currently, such requests result in:
```
[2]   readium-desktop:main#redux/sagas/api Error: self signed certificate
[2]   readium-desktop:main#redux/sagas/api     at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
[2]   readium-desktop:main#redux/sagas/api     at TLSSocket.emit (events.js:203:13)
[2]   readium-desktop:main#redux/sagas/api     at TLSSocket._finishInit (_tls_wrap.js:792:8)
[2]   readium-desktop:main#redux/sagas/api     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12) +41ms
```
with a white screen of death in the application.  Cert .pem is installed locally as a trusted source.

**Comment by llemeurfr** [comment]
To be discussed.

**Comment by danielweck** [comment]
This was fixed some time ago via HTTPS agent z`rejectUnauthorizedz`
https://github.com/edrlab/thorium-reader/blob/5b095fcec33edce32fdc066474954ac4605de91a/src/main/network/http.ts#L234-L237
